name: 100SuperHumans
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1745032148901373
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Coaching Therapy Counseling Teaching Internship
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffdff'
    - '#1f100b'
    - '#a6a7a9'
    - '#ffcf69'
    - '#b85905'
  brandStrength: 0.7807798618450761
  lightness: 0.1863591708242893
  saturation: 0.4934195196256042
  rhythmicContrast: 0.1000633903313428
purpose: []
